### ISSUE TITLE
[FEATURE] Need a shortcut for Next

### ISSUE THREAD

**Issue by ObeyYourHeart** [bjsi/incremental-everything#10]
The keyboard mode is a very smooth incremental mode!

**Comment by ObeyYourHeart** [comment]
It would be nice if users could customize it.
I would recommend F7.
Because opening the incremental queue is like opening RemNote, keys such as Ctrl, Alt, Shift and so on are almost inconvenient.
F7 will not have any impact in browsers and applications

**Comment by bjsi** [comment]
I added a command without a default shortcut. So you can choose your own :+1:
