### ISSUE TITLE
Priority Change Issue

### ISSUE THREAD

**Issue by AkiraTheSquid** [bjsi/incremental-everything#12]
![RemNote_qTxYRuSBr5](https://github.com/bjsi/incremental-everything/assets/87283170/fb8e88a1-39bb-4a1e-86a7-247fcff959fa)

When I try to change the priority of an extract by deleting the first number, it won't let me. So I basically have to put the curser before the number and then type the new number to go to something like 67, which is really annoying. Just try to delete the whole number and put a new one yourself. It can't be done.

**Comment by bjsi** [comment]
fixed :) coming in the next release
