### ISSUE TITLE
Image Occlusion Cards not shown in queue.Probably a bug ?

### ISSUE THREAD

**Issue by webtaphip** [bjsi/incremental-everything#18]
Step 1 - Creating area highlight + Tagging with incremental . 

https://github.com/bjsi/incremental-everything/assets/143251037/cd731872-3360-499a-860e-1e3ec58ba627

Step 2 - Creating Image occlusion Cards.

https://github.com/bjsi/incremental-everything/assets/143251037/70719054-51a9-4436-b826-d0e283ea80bd

Step 3 -Practising occlusion card .

https://github.com/bjsi/incremental-everything/assets/143251037/5bedcae7-ec61-4411-85be-8f79edfe5e65

On refreshing , image occluded card is shown . But, then it shifts to incremental rem

https://github.com/bjsi/incremental-everything/assets/143251037/facafdc3-8991-4443-a3e1-97d937890887

**Comment by webtaphip** [comment]
@bjsi - Would it be possible to resolve this a bit early ? 🙏This issue renders the plugin a hindrance to use .

**Comment by bjsi** [comment]
I think I found a fix for the incremental tag + flashcard issue, but it requires a plugin SDK update and a remnote update :sweat_smile: so should be fixed ~this week hopefully.
