### ISSUE TITLE
[FEATURE] Button in the Queue for Untagging as Incremental

### ISSUE THREAD

**Issue by hugomarins** [bjsi/incremental-everything#22]
It would make it easier for the user, when consider himself done with that material, exclude it form the incremental schedule.

**Describe the solution you'd like**
- In the Queue 3 dots options, to add a "Untag Incremental" command.
![image](https://github.com/bjsi/incremental-everything/assets/54500828/9ee25143-a67d-43bb-b761-2343319ef696)

- In the PDF Reader, transforme the puzzle button in a toggle type button (used for tagging as well as for untagging as Incremental).
![image](https://github.com/bjsi/incremental-everything/assets/54500828/a51266d5-399a-436b-a9d4-2165daed21c2)

**Comment by bjsi** [comment]
done :) coming in next release
