### ISSUE TITLE
[bug] /inc doesn't work on multiple Rem /extract only works on the parent level

### ISSUE THREAD

**Issue by ObeyYourHeart** [bjsi/incremental-everything#30]
![录制_2023_09_03_08_43_49_49](https://github.com/bjsi/incremental-everything/assets/114028910/c7551637-0e79-4aa4-abbf-0bef20633f18)
/inc doesn't work on multiple Rem

![录制_2023_09_03_08_44_41_423](https://github.com/bjsi/incremental-everything/assets/114028910/5be88233-7ce7-4cd4-90c0-7ff892617cb9)
/extract only works on the parent level

**Comment by bjsi** [comment]
fixed

**Comment by ObeyYourHeart** [comment]
Select all /inc, but sub-levels won't join /inc, is this the expected behavior?
![录制_2023_09_05_11_49_24_704](https://github.com/bjsi/incremental-everything/assets/114028910/cf309af5-6421-4d43-91f0-5bce2657e8d1)
it is same with /extract only works on the parent level .
