### ISSUE TITLE
[FEATURE] need a command for cancel the incremental Tag of the selected rem

### ISSUE THREAD

**Issue by ObeyYourHeart** [bjsi/incremental-everything#31]
![录制_2023_09_03_08_46_24_476](https://github.com/bjsi/incremental-everything/assets/114028910/8246cb08-fd4c-4580-aba3-b55ed8120426)
Deleting one by one is extremely inefficient

This setting is also required for "hide in the queue"plugin.

**Comment by bjsi** [comment]
added
