### ISSUE TITLE
[Bug] Incremental Everything not starting

### ISSUE THREAD

**Issue by AkiraTheSquid** [bjsi/incremental-everything#43]
All of a sudden Incremental everything is not ever showing up. I have it enabled in plugins but when I go to study by deck it is nowhere to be found:
![image](https://github.com/bjsi/incremental-everything/assets/87283170/c555db2b-03c0-41f5-b3e7-5c2da82d4595)
![image](https://github.com/bjsi/incremental-everything/assets/87283170/135afaf3-7fe8-48b3-a498-31e2436fc65a)
![image](https://github.com/bjsi/incremental-everything/assets/87283170/bd6f2b13-57a0-4528-91af-5ba41bdc70bb)

Update: It mysteriously came back:
<img width="1280" alt="image" src="https://github.com/bjsi/incremental-everything/assets/87283170/ed440282-1069-4693-baf9-f7509b36bf07">

**Comment by bjsi** [comment]
I think it's because the queue shows you "sub-day interval cards" (cards with an interval of < 24 hrs) before it shows plugin cards. I need to change the queue code to fix this :+1:

**Comment by bjsi** [comment]
should be fixed in an upcoming remnote update
