### ISSUE TITLE
[Bug] Queue showing same card over & over 

### ISSUE THREAD

**Issue by webtaphip** [bjsi/incremental-everything#46]
Issue - Queue keeps showing same cards over & over endlessly .

https://github.com/bjsi/incremental-everything/assets/143251037/9294f4a3-fff2-40c4-b715-c40db6623682

*might be due to the incremental rem have cloze & forward cards 🤔

**Comment by bjsi** [comment]
Yeah I think it's due to the incremental tag on the flashcards. I think I found a fix for this issue, but it requires a plugin SDK update and a remnote update :sweat_smile: so should be fixed ~this week hopefully.

**Comment by bjsi** [comment]
Should be fixed in the latest version
