### ISSUE TITLE
Forced reading of highlight prevents reading sections with a priority extract

### ISSUE THREAD

**Issue by AkiraTheSquid** [bjsi/incremental-everything#8]
![NsYEDf0](https://github.com/bjsi/incremental-everything/assets/87283170/aab27f5a-0499-4556-98cb-108058b72c3e)

you mentioned that if one wanted to extract a section of a pdf, then one could just extract the title and read below.
In practice, this cannot be done, however, because of the solution you had for moving to a part of a pdf in the incremental reading queue. That is to say, it forces you to be at that part at all times. So if you try to scroll down at all it just brings you back up to the section heading, so you cannot actually incrementally read a section within the incremental reader if you try to use this method of highlighting the section heading.

Even if you try to highlight the entire section it won't let you read that section in the incremental queue because it then changes to forcing you to read the _center_ of that highlight:

![xtLaJeR](https://github.com/bjsi/incremental-everything/assets/87283170/9d5bb005-c2ef-4596-a032-a0c261fe0ac8)

**Comment by bjsi** [comment]
oof yeah that's very annoying, fixed :) will be in the next release
